config/routes.rb
Rails.application.routes.draw do
  get 'intro',        to: 'static_pages#intro', as: :intro
  get 'type_of_care', to: 'static_pages#type_of_care'
  get 'caregivers',   to: 'static_pages#caregivers'
  get 'procedure',    to: 'static_pages#procedure'
  get 'servicearea',  to: 'static_pages#servicearea'
  get 'cost',         to: 'static_pages#cost'
  get 'testimonials', to: 'static_pages#testimonials', as: :testimonials # to specify anchor
  get 'contactus',    to: 'static_pages#contactus', as: :contactus
  get 'print',        to: 'static_pages#print'

  root 'static_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def type_of_care
		@body_id = 'care'
	end

	def caregivers
		@body_id = 'caregivers'
	end

	def contactus
		@body_id = 'contactus'
	end

	def cost
		@body_id = 'cost'
	end

	# The root is routed here
	def index
		render layout: false
	end

	def intro
		@body_id = 'intro'
	end

	def print
		@body_id = 'print'
		render :layout => false
	end

	def procedure
		@body_id = 'procedure'
	end

	def servicearea
		@body_id = 'servicearea'
	end

	def testimonials
		@body_id = 'testimonials'
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def javascript_google_tag
    return unless ENV['GA_MEASUREMENT_ID']

    content_tag(:script, '',
      async: true,
      src: "https://www.googletagmanager.com/gtag/js?id=#{ENV['GA_MEASUREMENT_ID']}",
      data: {
        controller: "google-tag",
        # Pass server-side (ENV var, here) value to the client (JS; Stimulus)
        google_tag_measurement_id_value: ENV['GA_MEASUREMENT_ID']
      }
    )
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/application/_menu_nav_shared_items.html.haml
%li= link_to 'Welcome', intro_path
%li= link_to 'Type of Care', type_of_care_path
%li= link_to 'Caregivers', caregivers_path
%li= link_to 'Procedure', procedure_path
%li= link_to 'Service area', servicearea_path
%li= link_to 'Cost', cost_path
%li= link_to 'Testimonials', testimonials_path
%li= link_to 'Contact us ...', contactus_path

app/views/layouts/application.html.haml
!!!
%html
	%head
		%meta{ charset: 'utf-8' }
		%meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0' }
		%meta{ name: 'gp-gm-api-key', content: ENV['GP_GOOGLE_MAPS_API_KEY'] }
		%meta{ name: 'gp-gm-map-id', content: ENV['GP_GOOGLE_MAPS_MAP_ID'] }
		%script{ src: "https://kit.fontawesome.com/a46ffabf68.js", crossorigin: "anonymous" }
		%title Good People LLC - Live-in caregivers & companions
		= stylesheet_link_tag	'application', media: 'all'
		= javascript_importmap_tags
		= javascript_google_tag
		= csrf_meta_tags
		= csp_meta_tag

	%body.body--interior-pg
		.off-canvas#offCanvas.position-left{ data: { off_canvas: true } }
			%nav
				%ul.menu.vertical{ data: { controller: "current-nav-item" } }
					%li
						= link_to root_path do
							= render 'svg_gp_logo_logomark'
					= render 'menu_nav_shared_items'
					%li &nbsp;
					%li= link_to '1-800-608-8003', 'tel:18006088003', class: 'a--gp-contact-info'
					%li= link_to 'info@goodpeople.us', 'mailto:info@goodpeople.us', class: 'a--gp-contact-info'

		.off-canvas-content{ data: { off_canvas_content: true } }
			%header.header--mobile-interior-pg
				.left--header--mobile
					.off-canvas-opener
						%button.menu-icon{ type: 'button', data: { toggle: 'offCanvas' } }
							%label.label--off-canvas-opener Menu
				.right--header--mobile
					.gp-contact-info--header--mobile
						= link_to '1-800-608-8003', 'tel:18006088003', class: 'a--gp-contact-info'
						= link_to 'info@goodpeople.us', 'mailto:info@goodpeople.us', class: 'a--gp-contact-info'

			.gridfield
				%header.header--desktop-interior-pg
					= render 'header_desktop'
				%nav.nav--desktop-interior-pg
					%ul.menu.vertical{ data: { controller: "current-nav-item" } }
						= render 'menu_nav_shared_items'
						%li
							= link_to print_path, class: 'a--print' do
								%i.fas.fa-print &nbsp;
								%span Print view

				%main.main--interior-pg
					= yield

				%footer.footer--interior-pg
					%p.p-footer &copy; 2001 - #{Date.today.year} Good People, LLC

app/views/static_pages/_care.html.haml
%p Good People will match any need. It can be a companionship, it can be a temporary help to recover from a stroke or a hip fracture, or it can be taking care of terminally ill person. Our caregivers are attending patients with Alzheimer's disease, dementia, Parkinson's, multiple sclerosis, cerebral palsy, brain injuries, emphysema, cancer and other illnesses. We also work closely with Hospices.

%p Caregiver lives in the home of the care receiver and is ready to help 24 hours a day!

%p <strong>Caregiver's responsibilities consist of:</strong>

%ul
	%li <strong>Personal care</strong> - caregivers help with ambulation, transfers, repositioning, bathing, toileting, daily exercises, getting up at night, dressing, feeding, coordinating doctor, therapist and other appointments & providing escort (where car is available), administering/monitoring medications, oxygen, fluid regime, special diet, and other personal care related tasks ...
	%li <strong>House making</strong> - cooking, serving the meals, doing the dishes, laundry, dusting, vacuuming, mopping the floors, watering the plants, walking the dog or cleaning the cat litter, grocery shopping, paying the bills, and other daily chores around the house ...
	%li <strong>Companionship</strong> - chatting, personal shopping, assisting in telephone calls, eating meals together, playing cards, reading papers, watching movies, sorting mail, sending postcards, and other "little" pleasures add to care receiver's overall health and happiness. Mental and physical stimulation are essential for success of the placement.

%p Naturally, live-in caregivers become part of a family. They create safe and comfortable atmosphere filled with dignity and compassion.

%p Responsibilities and activities mentioned above are to illustrate what you can realistically expect. Every care receiver, however, is different and has individual needs and wants. <strong>The service is flexible</strong> and we will exact the level of help during our evaluation and assessment interview. And also, caregivers apply their common sense and feel for the situation.

%p Live-in caregivers need time off during the day to relax. They need at least an hour in the morning and in the afternoon, or a workable equivalent. Caregivers like to go for a walk, to gym, swimming or jogging. Good time for these breaks are care receiver's naps or visits. If the care receiver plans on having a longer visit, let the caregiver go to a library or to see a movie. With a regular time off and away from the job, your caregiver will be a much better provider of care.

app/views/static_pages/_header.html.haml
// 6 columns to prevent too early resizing
.column.small-6
	=image_tag "GP Logo web1.gif", border:"0", usemap:"#Map", href:"#"
	%map{ name:"Map" }
		%area{ shape:"rect", coords:"4,4,298,150", href:map_ref }
// <6 (to get <12 together), this will make the last column float to R
.column.small-4
	.gp-contact-info--header-desktop
		=link_to '1-800-608-8003', 'tel:18006088003', class:'a-gp-contact-info'
		=link_to 'info@goodpeople.us', 'mailto:info@goodpeople.us', class:'a-gp-contact-info'

app/views/static_pages/_header_desktop.html.haml
- if local_assigns[:for_print]
	= link_to root_path do
		= render 'svg_gp_logo_complete', class_name: 'svg--gp-logo-print-pg'

	.gp-contact-info--header--desktop
		.a--gp-contact-info 1-800-608-8003
		.a--gp-contact-info info@goodpeople.us

- else
	= link_to root_path do
		= render 'svg_gp_logo_complete', class_name: 'svg--gp-logo-desktop'

	.gp-contact-info--header--desktop
		= link_to '1-800-608-8003', 'tel:18006088003', class:'a--gp-contact-info'
		= link_to 'info@goodpeople.us', 'mailto:info@goodpeople.us', class:'a--gp-contact-info'

app/views/static_pages/_index_call_to_action.html.haml
- btn_text = 'Learn More'

.row
	.columns.small-centered.small-7
		%nav
			= link_to btn_text, intro_path, class:'btn-cta-learn-more'

.row
	.columns.small-centered.small-12.medium-8
		.gp-contact-info--index-pg
			=link_to '1-800-608-8003', 'tel:18006088003', class:'a-gp-contact-info'
			=link_to 'info@goodpeople.us', 'mailto:info@goodpeople.us', class:'a-gp-contact-info'

app/views/static_pages/_type_of_care.html.haml
%p Good People will match any need. It can be a companionship, it can be a temporary help to recover from a stroke or a hip fracture, or it can be taking care of terminally ill person. Our caregivers are attending patients with Alzheimer's disease, dementia, Parkinson's, multiple sclerosis, cerebral palsy, brain injuries, emphysema, cancer and other illnesses. We also work closely with Hospices.

%p Caregiver lives in the home of the care receiver and is ready to help 24 hours a day!

%p <strong>Caregiver's responsibilities consist of:</strong>

%ul
	%li <strong>Personal care</strong> - caregivers help with ambulation, transfers, repositioning, bathing, toileting, daily exercises, getting up at night, dressing, feeding, coordinating doctor, therapist and other appointments & providing escort (where car is available), administering/monitoring medications, oxygen, fluid regime, special diet, and other personal care related tasks ...
	%li <strong>House making</strong> - cooking, serving the meals, doing the dishes, laundry, dusting, vacuuming, mopping the floors, watering the plants, walking the dog or cleaning the cat litter, grocery shopping, paying the bills, and other daily chores around the house ...
	%li <strong>Companionship</strong> - chatting, personal shopping, assisting in telephone calls, eating meals together, playing cards, reading papers, watching movies, sorting mail, sending postcards, and other "little" pleasures add to care receiver's overall health and happiness. Mental and physical stimulation are essential for success of the placement.

%p Naturally, live-in caregivers become part of a family. They create safe and comfortable atmosphere filled with dignity and compassion.

%p Responsibilities and activities mentioned above are to illustrate what you can realistically expect. Every care receiver, however, is different and has individual needs and wants. <strong>The service is flexible</strong> and we will exact the level of help during our evaluation and assessment interview. And also, caregivers apply their common sense and feel for the situation.

%p Live-in caregivers need time off during the day to relax. They need at least an hour in the morning and in the afternoon, or a workable equivalent. Caregivers like to go for a walk, to gym, swimming or jogging. Good time for these breaks are care receiver's naps or visits. If the care receiver plans on having a longer visit, let the caregiver go to a library or to see a movie. With a regular time off and away from the job, your caregiver will be a much better provider of care.

app/views/static_pages/caregivers.html.haml
%h1.h1--interior-pg Caregivers
=render 'caregivers'

app/views/static_pages/cost.html.haml
%h1.h1--interior-pg Cost
=render 'cost'

app/views/static_pages/intro.html.haml
%h1.h1--interior-pg Welcome
=render 'intro'

app/views/static_pages/print.html.haml
!!!
%html
	%head
		%title Good People LLC - Live-in caregivers & companions
		= stylesheet_link_tag	'application', media: 'all'
		= javascript_importmap_tags
		= javascript_google_tag
		= csrf_meta_tags
		= csp_meta_tag

	%body

		%header.header--print-pg
			= render partial: 'header_desktop', locals: { for_print: true }

		%main.main--print-pg
			%h1.h1--print-pg= link_to 'Intro', :action => :intro
			= render 'intro'
			%br

			%h1.h1--print-pg= link_to 'Care', :action => :type_of_care
			= render 'type_of_care'
			%br

			%h1.h1--print-pg= link_to 'Caregivers', :action => :caregivers
			= render 'caregivers'
			%br

			%h1.h1--print-pg= link_to 'Procedure', :action => :procedure
			= render 'procedure'
			%br

			%h1.h1--print-pg= link_to 'Service area', :action => :servicearea
			= render 'servicearea'
			%br

			%h1.h1--print-pg= link_to 'Cost', :action => :cost
			= render 'cost'
			%br

			%h1.h1--print-pg= link_to 'Contact us', :action => :contactus
			= render 'contactus'

app/views/static_pages/procedure.html.haml
%h1.h1--interior-pg Procedure
=render 'procedure'

app/views/static_pages/servicearea.html.haml
%h1.h1--interior-pg Service area
=render 'servicearea'
.min-height.show-for-small-only

app/views/static_pages/testimonials.html.haml
%h1.h1--interior-pg Testimonials
=render 'testimonials'

app/views/static_pages/type_of_care.html.haml
%h1.h1--interior-pg Type and level of care you can receive
=render 'type_of_care'